name: 'UnityPackage Icon Adder'
description: 'Add a custom icon to a Unity package'
icon: 'image'
color: 'blue'
inputs:
  package_path:
    description: 'Path to the Unity package'
    required: true
  icon_path:
    description: 'Path to the icon'
    required: true
  icon_not_found_behavior:
    description: 'What to do if the icon is not found (fail, warn, ignore)'
    required: false
    default: 'fail'
  package_not_found_behavior:
    description: 'What to do if the package is not found (fail, warn, ignore)'
    required: false
    default: 'fail'
runs:
  using: 'node12'
  main: 'index.js'
